# Generated by Django 5.2.11 on 2026-03-02 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('best_time', models.FloatField(blank=True, null=True, verbose_name='Лучшее время')),
            ],
            options={
                'verbose_name': 'Пользователь (простая таблица)',
                'verbose_name_plural': 'Пользователи (простая таблица)',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterModelOptions(
            name='leaderboard',
            options={'ordering': ['time'], 'verbose_name': 'Рекорд', 'verbose_name_plural': 'Рекорды'},
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='mines',
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='time',
            field=models.FloatField(help_text='Время в секундах с точностью 0.001', verbose_name='Время (секунды)'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.simpleuser'),
        ),
        migrations.DeleteModel(
            name='GameResult',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
