# Generated by Django 5.2.11 on 2026-03-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_simpleuser_remove_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleuser',
            name='data_top_game',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата лучшей игры'),
        ),
    ]
